require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentRelationshipsController do

  # This should return the minimal set of attributes required to create a valid
  # CommentRelationship. As you add validations to CommentRelationship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentRelationshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all comment_relationships as @comment_relationships" do
      comment_relationship = CommentRelationship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comment_relationships).should eq([comment_relationship])
    end
  end

  describe "GET show" do
    it "assigns the requested comment_relationship as @comment_relationship" do
      comment_relationship = CommentRelationship.create! valid_attributes
      get :show, {:id => comment_relationship.to_param}, valid_session
      assigns(:comment_relationship).should eq(comment_relationship)
    end
  end

  describe "GET new" do
    it "assigns a new comment_relationship as @comment_relationship" do
      get :new, {}, valid_session
      assigns(:comment_relationship).should be_a_new(CommentRelationship)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment_relationship as @comment_relationship" do
      comment_relationship = CommentRelationship.create! valid_attributes
      get :edit, {:id => comment_relationship.to_param}, valid_session
      assigns(:comment_relationship).should eq(comment_relationship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommentRelationship" do
        expect {
          post :create, {:comment_relationship => valid_attributes}, valid_session
        }.to change(CommentRelationship, :count).by(1)
      end

      it "assigns a newly created comment_relationship as @comment_relationship" do
        post :create, {:comment_relationship => valid_attributes}, valid_session
        assigns(:comment_relationship).should be_a(CommentRelationship)
        assigns(:comment_relationship).should be_persisted
      end

      it "redirects to the created comment_relationship" do
        post :create, {:comment_relationship => valid_attributes}, valid_session
        response.should redirect_to(CommentRelationship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment_relationship as @comment_relationship" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommentRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:comment_relationship => {}}, valid_session
        assigns(:comment_relationship).should be_a_new(CommentRelationship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommentRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:comment_relationship => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment_relationship" do
        comment_relationship = CommentRelationship.create! valid_attributes
        # Assuming there are no other comment_relationships in the database, this
        # specifies that the CommentRelationship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommentRelationship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comment_relationship.to_param, :comment_relationship => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested comment_relationship as @comment_relationship" do
        comment_relationship = CommentRelationship.create! valid_attributes
        put :update, {:id => comment_relationship.to_param, :comment_relationship => valid_attributes}, valid_session
        assigns(:comment_relationship).should eq(comment_relationship)
      end

      it "redirects to the comment_relationship" do
        comment_relationship = CommentRelationship.create! valid_attributes
        put :update, {:id => comment_relationship.to_param, :comment_relationship => valid_attributes}, valid_session
        response.should redirect_to(comment_relationship)
      end
    end

    describe "with invalid params" do
      it "assigns the comment_relationship as @comment_relationship" do
        comment_relationship = CommentRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommentRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment_relationship.to_param, :comment_relationship => {}}, valid_session
        assigns(:comment_relationship).should eq(comment_relationship)
      end

      it "re-renders the 'edit' template" do
        comment_relationship = CommentRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommentRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment_relationship.to_param, :comment_relationship => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment_relationship" do
      comment_relationship = CommentRelationship.create! valid_attributes
      expect {
        delete :destroy, {:id => comment_relationship.to_param}, valid_session
      }.to change(CommentRelationship, :count).by(-1)
    end

    it "redirects to the comment_relationships list" do
      comment_relationship = CommentRelationship.create! valid_attributes
      delete :destroy, {:id => comment_relationship.to_param}, valid_session
      response.should redirect_to(comment_relationships_url)
    end
  end

end
