require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UpvoteRelationshipsController do

  # This should return the minimal set of attributes required to create a valid
  # UpvoteRelationship. As you add validations to UpvoteRelationship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UpvoteRelationshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all upvote_relationships as @upvote_relationships" do
      upvote_relationship = UpvoteRelationship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:upvote_relationships).should eq([upvote_relationship])
    end
  end

  describe "GET show" do
    it "assigns the requested upvote_relationship as @upvote_relationship" do
      upvote_relationship = UpvoteRelationship.create! valid_attributes
      get :show, {:id => upvote_relationship.to_param}, valid_session
      assigns(:upvote_relationship).should eq(upvote_relationship)
    end
  end

  describe "GET new" do
    it "assigns a new upvote_relationship as @upvote_relationship" do
      get :new, {}, valid_session
      assigns(:upvote_relationship).should be_a_new(UpvoteRelationship)
    end
  end

  describe "GET edit" do
    it "assigns the requested upvote_relationship as @upvote_relationship" do
      upvote_relationship = UpvoteRelationship.create! valid_attributes
      get :edit, {:id => upvote_relationship.to_param}, valid_session
      assigns(:upvote_relationship).should eq(upvote_relationship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UpvoteRelationship" do
        expect {
          post :create, {:upvote_relationship => valid_attributes}, valid_session
        }.to change(UpvoteRelationship, :count).by(1)
      end

      it "assigns a newly created upvote_relationship as @upvote_relationship" do
        post :create, {:upvote_relationship => valid_attributes}, valid_session
        assigns(:upvote_relationship).should be_a(UpvoteRelationship)
        assigns(:upvote_relationship).should be_persisted
      end

      it "redirects to the created upvote_relationship" do
        post :create, {:upvote_relationship => valid_attributes}, valid_session
        response.should redirect_to(UpvoteRelationship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved upvote_relationship as @upvote_relationship" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpvoteRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:upvote_relationship => {}}, valid_session
        assigns(:upvote_relationship).should be_a_new(UpvoteRelationship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpvoteRelationship.any_instance.stub(:save).and_return(false)
        post :create, {:upvote_relationship => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested upvote_relationship" do
        upvote_relationship = UpvoteRelationship.create! valid_attributes
        # Assuming there are no other upvote_relationships in the database, this
        # specifies that the UpvoteRelationship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UpvoteRelationship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => upvote_relationship.to_param, :upvote_relationship => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested upvote_relationship as @upvote_relationship" do
        upvote_relationship = UpvoteRelationship.create! valid_attributes
        put :update, {:id => upvote_relationship.to_param, :upvote_relationship => valid_attributes}, valid_session
        assigns(:upvote_relationship).should eq(upvote_relationship)
      end

      it "redirects to the upvote_relationship" do
        upvote_relationship = UpvoteRelationship.create! valid_attributes
        put :update, {:id => upvote_relationship.to_param, :upvote_relationship => valid_attributes}, valid_session
        response.should redirect_to(upvote_relationship)
      end
    end

    describe "with invalid params" do
      it "assigns the upvote_relationship as @upvote_relationship" do
        upvote_relationship = UpvoteRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpvoteRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => upvote_relationship.to_param, :upvote_relationship => {}}, valid_session
        assigns(:upvote_relationship).should eq(upvote_relationship)
      end

      it "re-renders the 'edit' template" do
        upvote_relationship = UpvoteRelationship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpvoteRelationship.any_instance.stub(:save).and_return(false)
        put :update, {:id => upvote_relationship.to_param, :upvote_relationship => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested upvote_relationship" do
      upvote_relationship = UpvoteRelationship.create! valid_attributes
      expect {
        delete :destroy, {:id => upvote_relationship.to_param}, valid_session
      }.to change(UpvoteRelationship, :count).by(-1)
    end

    it "redirects to the upvote_relationships list" do
      upvote_relationship = UpvoteRelationship.create! valid_attributes
      delete :destroy, {:id => upvote_relationship.to_param}, valid_session
      response.should redirect_to(upvote_relationships_url)
    end
  end

end
